### PR TITLE
Add possible fix for message order bug

### PR DESCRIPTION
**Pull request by dtersoff**
Sorts messages by createdAt date before displaying them. Will have to
deploy in order to test, since this bug has yet to appear locally

### CODE REVIEW

**Comment by marcpelve** [comment]
Probably has something to do with multiple clients hitting the database and then retrieving. Didn't really thoroughly test that situation.

**Comment by kimdolion** [comment]
Should we just force the sort to be safe though?

**Comment by dtersoff** [comment]
Well, give it a once-over to make sure I didn't miss something, and then we can merge it to the master branch

**Comment by marcpelve** [comment]
Do we really want to implement it for the presentation?

**Comment by dtersoff** [comment]
Probably not?

**Comment by marcpelve** [comment]
Well it looks like it'll work, there doesn't seem to be a problem. Have you tested it locally to see if it at least doesn't look wrong.

**Comment by dtersoff** [comment]
yup, it still shows them in the proper order, so I didn't mix up and sort in reverse order.

**Comment by marcpelve** [comment]
Well then I think its good for the merge.

**Pull request merged**
